services:
  postgres:
    image: postgres:16
    container_name: cartracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cartracker
      POSTGRES_USER: cartracker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - cartracker_pgdata:/var/lib/postgresql/data
    networks:
      - cartracker-net

  n8n:
    image: n8nio/n8n:latest
    container_name: cartracker-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - cartracker-net

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    image: cartracker-scraper
    container_name: cartracker-scraper
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - cartracker_raw:/data/raw
    networks:
      - cartracker-net

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.2
    container_name: cartracker-dbt
    working_dir: /usr/app
    volumes:
      - ./dbt:/usr/app
    environment:
      DBT_PROFILES_DIR: /usr/app
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: cartracker
      PGUSER: cartracker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - cartracker-net
    profiles: ["tools"]

  dbt_runner:
    build:
      context: .
      dockerfile: dbt_runner/Dockerfile
    container_name: cartracker-dbt-runner
    restart: unless-stopped
    working_dir: /usr/app
    volumes:
      - ./dbt:/usr/app
      - ./dbt_runner/app.py:/usr/app/app.py
    environment:
      DBT_PROFILES_DIR: /usr/app
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: cartracker
      PGUSER: cartracker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - cartracker-net
    depends_on:
      - postgres
    # Optional: only needed if you want to hit it from your host browser/curl
    ports:
      - "8081:8080"



volumes:
  cartracker_pgdata:
    external: true
    name: cartracker_pgdata

  cartracker_raw:
    external: true
    name: cartracker_raw

  n8n_data:
    external: true
    name: n8n_data

networks:
  cartracker-net:
    external: true
